# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-28 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortyurl',
            name='shortcode',
            field=models.CharField(default='doradefaultshortcode', max_length=15),
            preserve_default=False,
        ),
    ]
