# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-28 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0003_auto_20200728_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortyurl',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='shortyurl',
            name='update',
        ),
    ]
