# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-29 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0005_auto_20200728_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortyurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shortyurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
