# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-29 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0006_auto_20200729_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortyurl',
            name='shortcode',
            field=models.CharField(blank=True, default='abc123', max_length=15, unique=True),
        ),
    ]
