# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-30 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import shorty.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0007_auto_20200729_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortyurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shorty.validators.validate_url, shorty.validators.validate_dot_com]),
        ),
    ]
