# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-31 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shorty', '0008_auto_20200730_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shorty_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shorty.shortyURL')),
            ],
        ),
    ]
